version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sph-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/app/restApi
    volumes:
      - ./restApi:/app/restApi
      - ./agents.db:/app/agents.db
    networks:
      - sph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/agents"]
      interval: 30s
      timeout: 10s
      retries: 3

  agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sph-agent
    command: python restApi/run_agent.py
    volumes:
      - ./restApi:/app/restApi
    environment:
      - PYTHONPATH=/app/restApi
      - SERVER_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - sph-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: sph-nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - sph-network
    restart: unless-stopped

networks:
  sph-network:
    driver: bridge

